name: create a multiple workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: running the job
        uses: actions/checkout@v4

  job2:
    runs-on: windows-latest
    steps:
      - name: run the job
        run: ping google.com